requires 'Rose::DB::Object';
requires 'DateTime';
requires 'DateTime::Format::Duration';
requires 'DBD::mysql', '<= 4.051';
requires 'Log::Log4perl';
requires 'File::Tail';
requires 'Log::Dispatch::FileRotate';
